#!/bin/bash
# This hook is sourced after this virtualenv is activated.

export DJANGO_SECRET_KEY="(hp5wbs72^w$t79!o#7^^a5)#c0$y#k8#my)1%0tn@x8g!-)9t"
export DEBUG="True"
export DATABASE_URL="postgres://eduardo:123@localhost:5432/friendthem" # format postgres://USER:PASSWORD@HOST:PORT/NAME
export ALLOWED_HOSTS="*"
export FACEBOOK_KEY="593750164289317" 
export FACEBOOK_SECRET="6cd1be0a9c268d81a984f44059229014"
export GOOGLE_OAUTH2_KEY="40082266099-prvuh3gnpmf1586aua110c5n8nvkahsh.apps.googleusercontent.com"
export GOOGLE_OAUTH2_SECRET="cYxHogIYDPtCpwWFwvNxYrXP"
export INSTAGRAM_KEY="24d50845c7184376b02a628d82db633f"
export INSTAGRAM_SECRET="a4a1cc884da94266b294a2cd8b59d8e3"
export LINKEDIN_KEY="77ghwarmzcyd44"
export LINKEDIN_SECRET="L8tXa4iHSNFOz2Io"
export TWITTER_KEY="bTUbdB7Vfn9NdUQ6V4Ghl5ASK"
export TWITTER_SECRET="PKYRe38BBx4OnWKSfyVNVUIcXP6vUHBQEPiGpsza4UFtYJs6OT"
