#!/bin/bash
# This hook is sourced after this virtualenv is activated.

export DJANGO_SECRET_KEY="(hp5wbs72^w$t79!o#7^^a5)#c0$y#k8#my)1%0tn@x8g!-)9t"
export DEBUG="True"
export DATABASE_URL="postgres://postgres:postgres@localhost:5432/friendthem" # format postgres://USER:PASSWORD@HOST:PORT/NAME
export ALLOWED_HOSTS="*"
export FACEBOOK_KEY="132737610735229"
export FACEBOOK_SECRET="d0fba1c39ee223cd0eec2e9df8fa519d"
export GOOGLE_OAUTH2_KEY="595911831950-bdgl2qkqlbk8suf2fsqkbqj9dnvchdmn.apps.googleusercontent.com"
export GOOGLE_OAUTH2_SECRET="2Cvq6YPPWCfS9kETmCOALE1v"
export INSTAGRAM_KEY="4ad6fd09cd6142b19c3a79abae5be586"
export INSTAGRAM_SECRET="eb68cb54e7b9409a97dfa55aefaf7695"
export LINKEDIN_KEY="77ghwarmzcyd44"
export LINKEDIN_SECRET="L8tXa4iHSNFOz2Io"
export TWITTER_KEY="BqTYDSkMAneHtTbtj60aZk4QX"
export TWITTER_SECRET="NNDWMHp4Lqpb8Tdt0QwFAZIFIwWJgnfM7rxp6e4y89TvbF0dpG"
