# Generated by Django 2.0.2 on 2018-04-27 20:54
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('user', 'device_id')},
        ),
    ]
