# Generated by Django 2.0.2 on 2018-04-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_auto_20180427_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='phone_number',
        ),
    ]
