# Generated by Django 2.0.2 on 2018-04-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_auto_20180427_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='device_id',
            field=models.CharField(max_length=36),
        ),
    ]
