# Generated by Django 2.0.2 on 2018-04-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0004_auto_20180430_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='device_id',
            field=models.UUIDField(),
        ),
    ]
