# Generated by Django 2.0.1 on 2018-01-23 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0003_auto_20180122_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
