# Generated by Django 2.0.1 on 2018-01-23 16:37

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0004_auto_20180123_1602'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
