# Generated by Django 2.0.1 on 2018-01-22 20:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0004_auto_20180122_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('picture', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to='core_auth.Profile'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='socialprofile',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='socialprofile',
            unique_together={('profile', 'provider')},
        ),
    ]
