# Generated by Django 2.0.1 on 2018-01-23 17:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0005_install_postgis'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Represented as (longitude, latitude)', null=True, srid=4326),
        ),
    ]
