# Generated by Django 2.0.1 on 2018-02-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0007_auto_20180125_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ghost_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
    ]
