# Generated by Django 2.0.1 on 2018-02-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0009_user_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='private_phone',
            field=models.BooleanField(default=True),
        ),
    ]
