# Generated by Django 2.0.2 on 2018-03-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0013_auto_20180305_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='private_phone',
            new_name='phone_is_private',
        ),
    ]
