# Generated by Django 2.0.2 on 2018-03-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0014_auto_20180307_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='private_email',
            new_name='email_is_private',
        ),
    ]
