# Generated by Django 2.0.2 on 2018-03-07 21:51

from django.db import migrations

def merge_social_profile_to_social_auth(apps, schema_director):
    SocialProfile = apps.get_model('core_auth', 'SocialProfile')
    SocialAuth = apps.get_model('social_django', 'UserSocialAuth')
    for social_profile in SocialProfile.objects.all():
        try:
            social_auth = SocialAuth.objects.get(
                provider=social_profile.provider, user=social_profile.user
            )
            social_auth.extra_data.update({'username': social_profile.username})
            social_auth.save()
        except SocialAuth.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        ('core_auth', '0015_auto_20180307_2037'),
    ]

    operations = [
        migrations.RunPython(merge_social_profile_to_social_auth),
        migrations.AlterUniqueTogether(
            name='socialprofile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='socialprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SocialProfile',
        ),
    ]
