# Generated by Django 2.0.2 on 2018-03-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0016_auto_20180307_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_is_private',
            field=models.BooleanField(default=False),
        ),
    ]
