# Generated by Django 2.0.2 on 2018-03-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0017_auto_20180314_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_random_email',
            field=models.BooleanField(default=False),
        ),
    ]
