# Generated by Django 2.0.2 on 2018-04-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0018_user_is_random_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutorial_complete',
            field=models.BooleanField(default=False),
        ),
    ]
