# Generated by Django 2.0.2 on 2018-04-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0019_user_tutorial_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connection_tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
