# Generated by Django 2.0.2 on 2018-05-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0020_auto_20180403_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
