# Generated by Django 2.0.1 on 2018-01-29 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('Twitter', 'Twitter'), ('snapchat', 'Snapchat')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('user_1', 'user_2', 'provider')},
        ),
    ]
