# Generated by Django 2.0.1 on 2018-02-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20180129_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('twitter', 'Twitter'), ('snapchat', 'Snapchat')], max_length=10),
        ),
    ]
