# Generated by Django 2.0.2 on 2018-05-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_auto_20180511_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('youtube', 'Youtube'), ('twitter', 'Twitter'), ('snapchat', 'Snapchat')], max_length=10),
        ),
    ]
