# Generated by Django 2.0.2 on 2018-04-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_auth', '0020_auto_20180403_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core_auth.user',),
        ),
    ]
