# Generated by Django 2.0.2 on 2018-04-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0020_auto_20180403_1602'),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCompetitionUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core_auth.user',),
        ),
    ]
